# Generated by Django 4.2.6 on 2023-10-29 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('employee_pay_per_day', models.IntegerField()),
                ('employee_ot_pay', models.IntegerField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employeedetails')),
            ],
        ),
    ]
