version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: daily_attendance/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./daily_attendance:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
